package me.itangqi.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table NOTE.
 */
public class Note {

    private Long id;
    /** Not-null value. */
    private String bookname;
    /** Not-null value. */
    private String bookpath;
    /** Not-null value. */
    private String bookimgUrl;
    private java.util.Date date;

    public Note() {
    }

    public Note(Long id) {
        this.id = id;
    }

    public Note(Long id, String bookname, String bookpath, String bookimgUrl, java.util.Date date) {
        this.id = id;
        this.bookname = bookname;
        this.bookpath = bookpath;
        this.bookimgUrl = bookimgUrl;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getBookname() {
        return bookname;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBookname(String bookname) {
        this.bookname = bookname;
    }

    /** Not-null value. */
    public String getBookpath() {
        return bookpath;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBookpath(String bookpath) {
        this.bookpath = bookpath;
    }

    /** Not-null value. */
    public String getBookimgUrl() {
        return bookimgUrl;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBookimgUrl(String bookimgUrl) {
        this.bookimgUrl = bookimgUrl;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

}
